# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 066693deee35fa28ba62c2c0ab903fa629956a84db0b35e861c2ad181c005b0b0e420501f200a57f83c7210faba2d810cc8bc458c5bea1dee344daac7a8d839b

test:
  secret_key_base: 4cd325286e919b4b6891501c5aa2e11a31c39cd7d083cd70376a91f75f101d6736328c774d24c427038a26c5c113981eda361953c8bc59ea91a55fd9c3929726

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
